Displaying Python virtualenv stuff
Got fed up of this new error:

virtualenvwrapper.sh: There was a problem running the initialization
hooks. If Python could not import the module
virtualenvwrapper.hook_loader, check that virtualenv has been installed
for
    VIRTUALENVWRAPPER_PYTHON=/home/swaroop/local/virtualenvs/default/bin/python
    and that PATH is set properly.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      ImportError: No module named virtualenvwrapper.hook_loader